---
# GPU Detection
- name: Check for NVIDIA GPU
  shell: lspci | grep -i nvidia
  register: nvidia_gpu_check
  failed_when: false
  changed_when: false

- name: Check for AMD GPU
  shell: lspci | grep -i amd
  register: amd_gpu_check
  failed_when: false
  changed_when: false

- name: Set GPU detection facts
  set_fact:
    has_nvidia_gpu: "{{ nvidia_gpu_check.rc == 0 }}"
    has_amd_gpu: "{{ amd_gpu_check.rc == 0 }}"

- name: Display GPU detection results
  debug:
    msg: |
      === GPU DETECTION ===
      NVIDIA GPU detected: {{ has_nvidia_gpu }}
      AMD GPU detected: {{ has_amd_gpu }}

- name: Install core desktop dependencies
  package:
    name:
      - rofi
      - dunst
      - picom
      - nitrogen  # Wallpaper management
      - feh  # Image viewer and wallpaper setter
      - xclip  # Clipboard utility
      - xorg
      - lightdm
      - network-manager-gnome
      - pavucontrol
      - pasystray
      - blueman
      - copyq
      - jq  # JSON parser for notification history
      - libnotify-bin
      - cinnamon-screensaver
      - x11-xserver-utils  # Contains xrandr, xset
      - xinput
      - x11-xkb-utils  # Contains setxkbmap
      - upower  # For power monitoring functionality
      - powertop  # For detailed power analysis
      - conky-all  # System monitor for desktop overlay
      - arandr  # GUI for monitor configuration
      - autorandr  # Automatic monitor configuration switching
    state: present
  ignore_errors: yes  # Some packages might not be available on all systems

- name: Install NVIDIA GPU packages
  package:
    name:
      - nvidia-utils-535  # Provides nvidia-smi for GPU monitoring
    state: present
  when: has_nvidia_gpu
  ignore_errors: yes

- name: Install AMD GPU packages
  package:
    name:
      - radeontop  # AMD GPU monitoring tool (alternative to amdgpu-top)
    state: present
  when: has_amd_gpu
  ignore_errors: yes

- name: Copy qtile.desktop session file
  copy:
    src: "{{ dev_home }}/.config/qtile/install/qtile.desktop"
    dest: /usr/share/xsessions/qtile.desktop
    mode: '0644'
    remote_src: yes

- name: Create .config directory for user
  file:
    path: "{{ dev_home }}/.config"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: '0755'