---
# Safe fish repository setup using information from failsafe-checks
- name: Clone or update fish dotfiles repository (safe mode)
  git:
    repo: "{{ fish_git_repo | default('git@github.com:stonecharioteer/dotfiles-fish.git') }}"
    dest: "{{ dev_home }}/.config/fish"
    version: main
    update: "{{ not fish_config_repo_exists }}"  # Only update if it's a new clone
    force: no  # Never force, to preserve local changes
  become_user: "{{ dev_user }}"
  when: not fish_config_repo_exists

- name: Leave existing fish repository untouched
  debug:
    msg: "Fish repository already exists - skipping any git operations"
  when: fish_config_repo_exists

- name: Display git status for existing fish repository
  shell: |
    cd {{ dev_home }}/.config/fish
    echo "=== Current Branch ==="
    git branch --show-current
    echo "=== Git Status ==="
    git status --porcelain
    echo "=== Uncommitted Changes ==="
    git diff --name-only
  become_user: "{{ dev_user }}"
  when: fish_config_repo_exists
  register: fish_git_status_result
  changed_when: false

- name: Show fish repository status
  debug:
    msg: |
      === FISH REPOSITORY STATUS ===
      {% if fish_config_repo_exists %}
      Repository exists - preserved existing checkout
      {{ fish_git_status_result.stdout }}
      {% else %}
      Repository cloned fresh from GitHub
      {% endif %}
  when: fish_config_repo_exists

- name: Ensure fish config directory ownership
  file:
    path: "{{ dev_home }}/.config/fish"
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    recurse: yes