---
# Home Computer Inventory using SSH config hostnames
# Uses hostnames from ~/.ssh/config - much cleaner!

all:
  vars:
    # Ansible will use SSH config for connection details
    ansible_python_interpreter: /usr/bin/python3
    
  children:
    workstations:
      hosts:
        desktop:
          # ansible_connection: local  # Uncomment if running from this machine
        x13-flow:       # ASUS Flow X13 laptop
        hp-pavilion:    # HP Pavilion laptop
        EQR5:          # Mini PC
          
    servers:
      hosts:
        storage:       # Storage server
        
    # Group by function  
    gui_machines:
      hosts:
        desktop:
        x13-flow:
        hp-pavilion:
        EQR5:
        
    headless_machines:
      hosts:
        storage:
        
    # Group by device type
    laptops:
      hosts:
        x13-flow:
        hp-pavilion:
        
    mini_pcs:
      hosts:
        EQR5:
        
    desktops:
      hosts:
        desktop: