# tasks for bare minimum server dependencies
---
- name: Install bare minimum dependencies
  become: true
  apt:
    pkg:
      - apt-transport-https
      - acl
      - build-essential
      - ca-certificates
      - checkinstall
      - curl
      - git
      - gnupg
      - htop
      - libbz2-dev
      - libffi-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - net-tools
      - pkg-config
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - python3-virtualenv
      - sqlite3
      - traceroute
      - tcl
      - vim
      - zlib1g-dev
    state: latest
    update_cache: false
  tags:
    - installations
    - apt
