- name: Install CLI tools that will make development faster
  tags:
    - tools
  block: 
    - name: Install starship.rs Prompt
      block:
        # TODO: Only install this when starship isn't already installed.
        - name: Download Starship Installer
          get_url:
            url: https://starship.rs/install.sh
            dest: /tmp/install-starship.sh
            mode: 0754
        - name: Install Starship
          become: true
          shell:
            cmd: ./install-starship.sh --yes
            chdir: /tmp/
    - name: Install developer velocity tools
      block:
        - name: Install developer velocity tools via package managers
          become: true
          apt:
            pkg:
              - cowsay
              - direnv
              - entr
              - fd-find
              - fortune-mod
              - fzf
              - httpie
              - lolcat
              - neofetch
              - ripgrep
              - screenfetch
              - tree
              - zoxide
            state: latest
        - name: Install developer velocity tools from source
          block:
            - name: Install cargo-binstall for faster binary downloads
              shell: |
                . "$HOME/.cargo/env"
                cargo install cargo-binstall
            - name: Install development tools via cargo-binstall
              shell: |
                . "$HOME/.cargo/env"
                cargo binstall bottom --no-confirm
                cargo binstall du-dust --no-confirm
                cargo binstall exa --no-confirm
                cargo binstall live-server --no-confirm
                cargo binstall tokei --no-confirm
                cargo binstall as-tree --no-confirm
                cargo binstall atuin --no-confirm
        - name: Install gum
          become: true
          tags:
            - gum
          block:
            - name: Add the charmbracelet gpg key
              apt_key:
                url: https://repo.charm.sh/apt/gpg.key
                state: present
            - name: Add the charmbracelet apt repository
              apt_repository:
                repo: 'deb https://repo.charm.sh/apt/ * *'
                state: present
            - name: Install charmbracelet/gum
              apt:
                pkg:
                  - gum
                update_cache: true
                state: present
