- name: Install CLI tools that will make development faster
  tags:
    - tools
  block: 
    - name: Install starship.rs Prompt
      block:
        # TODO: Only install this when starship isn't already installed.
        - name: Download Starship Installer
          get_url:
            url: https://starship.rs/install.sh
            dest: /tmp/install-starship.sh
            mode: 0754
        - name: Install Starship
          become: true
          shell:
            cmd: ./install-starship.sh --yes
            chdir: /tmp/
    - name: Install developer velocity tools
      block:
        - name: Install developer velocity tools via package managers
          become: true
          apt:
            pkg:
              - cowsay
              - direnv
              - entr
              - fd-find
              - fortune-mod
              - fzf
              - httpie
              - lolcat
              - neofetch
              - ripgrep
              - screenfetch
              - tree
              - zoxide
            state: latest
        - name: Install developer velocity tools from source
          block:
            - name: Install bottom, du-dust, exa and live-server
              shell: |
                . "$HOME/.cargo/env"
                cargo install bottom --locked
                cargo install du-dust
                cargo install exa
                cargo install live-server
                cargo install tokei
                cargo install as-tree
        - name: Install gum
          become: true
          tags:
            - gum
          block:
            - name: Add the charmbracelet gpg key
              apt_key:
                url: https://repo.charm.sh/apt/gpg.key
                state: present
            - name: Add the charmbracelet apt repository
              apt_repository:
                repo: 'deb https://repo.charm.sh/apt/ * *'
                state: present
            - name: Install charmbracelet/gum
              apt:
                pkg:
                  - gum
                update_cache: true
                state: present
