---
# Shell specific setup for a better development experience
- name: Install Shell improvements
  block:
    - name: Install Fish Shell
      become: true
      block:
        - name: Add Fish PPA
          apt_repository:
            repo: ppa:fish-shell/release-3
            state: present
        - name: Install fish shell
          apt:
            update_cache: yes
            state: present
            pkg: fish
        - name: Make fish the default shell
          shell:
            cmd: |
              usermod --shell /usr/bin/fish {{ansible_env.USER}}
    - name: Download my personal fish config and symlink it to the config folder
      shell:
        cmd: |
          if [ -L '{{ansible_env.HOME}}/code/tools/dotfiles/fish' ]; then 
            git clone 'git@github.com:stonecharioteer/dotfiles-fish' '{{ansible_env.HOME}}/code/tools/dotfiles/fish'
          fi
          rm -rf '{{ansible_env.HOME}}/.config/fish' && ln -s '{{ansible_env.HOME}}/code/tools/dotfiles/fish/fish' '{{ansible_env.HOME}}/.config/fish'
