- name: Install dependencies to build python from source.
  block:
    - name: Install Cpython Build Dependencies
      become: true
      apt:
        pkg: python3
        state: build-dep
        update_cache: true
    - name: Install additional dependencies to build python from source
      become: true
      apt:
        pkg:
          - build-essential
          - gdb
          - lcov
          - libbz2-dev 
          - libffi-dev
          - libgdbm-compat-dev 
          - libgdbm-dev 
          - liblzma-dev
          - libncurses5-dev 
          - libreadline6-dev 
          - libsqlite3-dev 
          - libssl-dev
          - lzma 
          - lzma-dev 
          - pkg-config
          - tk-dev 
          - uuid-dev 
          - zlib1g-dev
        state: present
