---
# Install and configure qtile
- name: Install and configure qtile
  block:
    - name: Check if qtile python is already installed
      stat:
        path: /opt/qtile/bin/python3.9
      register: qtile_binary
    - name: Create qtile directory with ownership set to the current user. 
      when: not qtile_binary.stat.exists
      become: true
      file:
        path: '/opt/qtile'
        # TODO: Figure out how to use the login user's name
        owner: 'stonecharioteer'
        state: directory
    - name: Install and configure qtile
      when: not qtile_binary.stat.exists
      shell:
        cmd: |
          wget --quiet https://www.python.org/ftp/python/3.9.15/Python-3.9.15.tar.xz
          tar -xvf Python-3.9.15.tar.xz
          cd Python-3.9.15
          ./configure --prefix=/opt/qtile --enable-optimizations
          make -s -j8
          make altinstall
        chdir: /tmp
    - name: Download and install the pystonecharioteer config.
      shell:
        cmd: /opt/qtile/bin/python3.9 -m pip install --force-reinstall --no-cache-dir stonecharioteer
    - name: Install additional dependencies for qtile
      become: true
      apt:
        state: present
        pkg:
          - autorandr
          - dunst
          - nitrogen
          - pasystray
          - pavucontrol
          - redshift
          - rofi
          - rofi
          - xfce4-power-manager
          - xscreensaver
    - name: Checkout the pystonecharioteer repo and link the config
      shell:
        cmd: |
          if [ -L '{{ansible_env.HOME}}/code/checkouts/personal/pystonecharioteer' ]; then 
            git clone git@github.com/stonecharioteer/pystonecharioteer '{{ansible_env.HOME}}/code/checkouts/personal/pystonecharioteer'
          fi
          mkdir -p '{{ansible_env.HOME}}/.config/qtile/'
          rm -rf '{{ansible_env.HOME}}/.config/qtile/config.py'
          ln -s '{{ansible_env.HOME}}/code/checkouts/personal/pystonecharioteer/config.py' '{{ansible_env.HOME}}/.config/qtile/config.py'
          rm -rf '{{ansible_env.HOME}}/.config/qtile/stonecharioteer.json'
          ln -s '{{ansible_env.HOME}}/code/checkouts/personal/pystonecharioteer/stonecharioteer.json' '{{ansible_env.HOME}}/.config/qtile/stonecharioteer.json'
    - name: Copy the qtile.desktop file
      become: true
      copy:
        src: '{{ansible_env.HOME}}/code/checkouts/personal/pystonecharioteer/qtile.desktop'
        dest: '/usr/share/xsessions/qtile.desktop'
        remote_src: true
