---
# macOS-specific AeroSpace installation
- name: Check if AeroSpace is installed
  stat:
    path: /Applications/AeroSpace.app
  register: aerospace_check
  become: no

- name: Install AeroSpace via Homebrew cask
  shell: |
    export HOMEBREW_NO_AUTO_UPDATE=1
    export PATH="/opt/homebrew/bin:$PATH"

    # Tap the repository if needed
    if ! brew tap | grep -q "^nikitabobko/tap$"; then
      echo "Tapping nikitabobko/tap..."
      brew tap nikitabobko/tap
    fi

    # Install AeroSpace
    if ! brew list --cask aerospace &>/dev/null; then
      echo "Installing AeroSpace..."
      brew install --cask aerospace
    else
      echo "AeroSpace is already installed"
    fi
  args:
    executable: /bin/bash
  become: no
  register: aerospace_install_result
  changed_when: "'Installing' in aerospace_install_result.stdout or 'Tapping' in aerospace_install_result.stdout"
  when: not aerospace_check.stat.exists

- name: Display AeroSpace installation output
  debug:
    msg: "{{ aerospace_install_result.stdout_lines }}"
  when: aerospace_install_result.stdout_lines is defined and not aerospace_check.stat.exists

- name: Create AeroSpace config directory
  file:
    path: "{{ dev_home }}/.config/aerospace"
    state: directory
    owner: "{{ dev_user }}"
    mode: '0755'
  become: no

- name: Copy custom AeroSpace configuration
  copy:
    src: aerospace.toml
    dest: "{{ dev_home }}/.config/aerospace/aerospace.toml"
    owner: "{{ dev_user }}"
    mode: '0644'
    force: yes
  become: no

- name: Verify AeroSpace installation
  stat:
    path: /Applications/AeroSpace.app
  register: aerospace_verify
  become: no

- name: Display AeroSpace installation status
  debug:
    msg: |
      {% if aerospace_verify.stat.exists %}
      ✓ AeroSpace tiling window manager installed at /Applications/AeroSpace.app
      ✓ Config directory: {{ dev_home }}/.config/aerospace
      ✓ Custom configuration deployed from role files

      📋 Next Steps:
      1. Launch AeroSpace from Applications or Spotlight
      2. Grant Accessibility permissions in System Preferences → Privacy & Security
      3. AeroSpace will start automatically at login
      4. Use Alt+h/j/k/l to navigate between windows
      5. Use Alt+1-9 to switch workspaces
      6. Use Alt+Shift+1-9 to move windows to workspaces
      7. Customize config at: {{ dev_home }}/.config/aerospace/aerospace.toml
      {% else %}
      ⚠ AeroSpace installation verification failed
      {% endif %}
