---
# macOS-specific AeroSpace installation
- name: Check if AeroSpace is installed
  stat:
    path: /Applications/AeroSpace.app
  register: aerospace_check
  become: no

- name: Install AeroSpace via Homebrew cask
  shell: |
    export HOMEBREW_NO_AUTO_UPDATE=1
    export PATH="/opt/homebrew/bin:$PATH"

    # Tap the repository if needed
    if ! brew tap | grep -q "^nikitabobko/tap$"; then
      echo "Tapping nikitabobko/tap..."
      brew tap nikitabobko/tap
    fi

    # Install AeroSpace
    if ! brew list --cask aerospace &>/dev/null; then
      echo "Installing AeroSpace..."
      brew install --cask aerospace
    else
      echo "AeroSpace is already installed"
    fi
  args:
    executable: /bin/bash
  become: no
  register: aerospace_install_result
  changed_when: "'Installing' in aerospace_install_result.stdout or 'Tapping' in aerospace_install_result.stdout"
  when: not aerospace_check.stat.exists

- name: Display AeroSpace installation output
  debug:
    msg: "{{ aerospace_install_result.stdout_lines }}"
  when: aerospace_install_result.stdout_lines is defined and not aerospace_check.stat.exists

- name: Create AeroSpace config directory
  file:
    path: "{{ dev_home }}/.config/aerospace"
    state: directory
    owner: "{{ dev_user }}"
    mode: '0755'
  become: no

- name: Clone AeroSpace dotfiles repository if configured
  git:
    repo: "{{ aerospace_dotfiles_repo }}"
    dest: "{{ dev_home }}/.config/aerospace"
    update: yes
    force: no
  become: no
  when: aerospace_dotfiles_repo is defined
  ignore_errors: yes

- name: Create default AeroSpace config if no dotfiles repo
  copy:
    content: |
      # AeroSpace configuration
      # https://github.com/nikitabobko/AeroSpace

      # Start AeroSpace at login
      start-at-login = true

      # Normalizations. See: https://nikitabobko.github.io/AeroSpace/guide#normalization
      enable-normalization-flatten-containers = true
      enable-normalization-opposite-orientation-for-nested-containers = true

      # Mouse follows focus
      on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

      # Gaps between windows
      [gaps]
      inner.horizontal = 8
      inner.vertical = 8
      outer.left = 8
      outer.bottom = 8
      outer.top = 8
      outer.right = 8

      # Mode declarations
      [mode.main.binding]
      alt-slash = 'layout tiles horizontal vertical'
      alt-comma = 'layout accordion horizontal vertical'

      # Focus navigation
      alt-h = 'focus left'
      alt-j = 'focus down'
      alt-k = 'focus up'
      alt-l = 'focus right'

      # Move windows
      alt-shift-h = 'move left'
      alt-shift-j = 'move down'
      alt-shift-k = 'move up'
      alt-shift-l = 'move right'

      # Workspaces
      alt-1 = 'workspace 1'
      alt-2 = 'workspace 2'
      alt-3 = 'workspace 3'
      alt-4 = 'workspace 4'
      alt-5 = 'workspace 5'
      alt-6 = 'workspace 6'
      alt-7 = 'workspace 7'
      alt-8 = 'workspace 8'
      alt-9 = 'workspace 9'

      # Move windows to workspaces
      alt-shift-1 = 'move-node-to-workspace 1'
      alt-shift-2 = 'move-node-to-workspace 2'
      alt-shift-3 = 'move-node-to-workspace 3'
      alt-shift-4 = 'move-node-to-workspace 4'
      alt-shift-5 = 'move-node-to-workspace 5'
      alt-shift-6 = 'move-node-to-workspace 6'
      alt-shift-7 = 'move-node-to-workspace 7'
      alt-shift-8 = 'move-node-to-workspace 8'
      alt-shift-9 = 'move-node-to-workspace 9'

      # Resize mode
      alt-r = 'mode resize'

      [mode.resize.binding]
      h = 'resize width -50'
      j = 'resize height +50'
      k = 'resize height -50'
      l = 'resize width +50'
      enter = 'mode main'
      esc = 'mode main'
    dest: "{{ dev_home }}/.config/aerospace/aerospace.toml"
    owner: "{{ dev_user }}"
    mode: '0644'
    force: no
  become: no
  when: aerospace_dotfiles_repo is not defined

- name: Verify AeroSpace installation
  stat:
    path: /Applications/AeroSpace.app
  register: aerospace_verify
  become: no

- name: Display AeroSpace installation status
  debug:
    msg: |
      {% if aerospace_verify.stat.exists %}
      ✓ AeroSpace tiling window manager installed at /Applications/AeroSpace.app
      ✓ Config directory: {{ dev_home }}/.config/aerospace
      {% if aerospace_dotfiles_repo is defined %}
      ✓ Dotfiles cloned from: {{ aerospace_dotfiles_repo }}
      {% else %}
      ✓ Default configuration created
      {% endif %}

      📋 Next Steps:
      1. Launch AeroSpace from Applications or Spotlight
      2. Grant Accessibility permissions in System Preferences → Privacy & Security
      3. AeroSpace will start automatically at login
      4. Use Alt+h/j/k/l to navigate between windows
      5. Use Alt+1-9 to switch workspaces
      6. Use Alt+Shift+1-9 to move windows to workspaces
      7. Customize config at: {{ dev_home }}/.config/aerospace/aerospace.toml
      {% else %}
      ⚠ AeroSpace installation verification failed
      {% endif %}
