---
- name: Install Python 3 and development tools
  package:
    name:
      - python3
      - python3-venv
      - python3-pip
      - build-essential
      - git
      - curl
      - wget
    state: present

- name: Install Fish shell
  package:
    name: fish
    state: present

- name: Check if user exists
  user:
    name: "{{ dev_user }}"
    state: present
  register: user_check
  ignore_errors: yes

- name: Create user if it doesn't exist
  user:
    name: "{{ dev_user }}"
    shell: /usr/bin/fish
    create_home: yes
    groups: sudo
    append: yes
  when: user_check is failed

- name: Set Fish as default shell for user
  user:
    name: "{{ dev_user }}"
    shell: /usr/bin/fish
  when: user_check is succeeded

- name: Create /opt/qtile directory
  file:
    path: "{{ qtile_venv_path }}"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: '0755'

- name: Create Pictures/screenshots directory for user
  file:
    path: "{{ dev_home }}/Pictures/screenshots"
    state: directory
    owner: "{{ dev_user }}"
    group: "{{ dev_user }}"
    mode: '0755'