---
- name: Check if tmux is already installed
  stat:
    path: "{{ tmux_binary_path }}"
  register: tmux_exists

- name: Display tmux installation status
  debug:
    msg: "tmux already installed at {{ tmux_binary_path }}"
  when: tmux_exists.stat.exists

- name: Install tmux from source
  block:
    - name: Install tmux build dependencies
      package:
        name: "{{ tmux_build_deps }}"
        state: present

    - name: Create build directory
      file:
        path: "{{ tmux_build_dir }}"
        state: directory
        mode: '0755'

    - name: Get latest tmux release info from GitHub
      uri:
        url: https://api.github.com/repos/tmux/tmux/releases/latest
        method: GET
        return_content: yes
      register: tmux_release_info

    - name: Set tmux download URL
      set_fact:
        tmux_download_url: "{{ tmux_release_info.json.tarball_url }}"
        tmux_tag: "{{ tmux_release_info.json.tag_name }}"

    - name: Download tmux source
      get_url:
        url: "{{ tmux_download_url }}"
        dest: "{{ tmux_build_dir }}/tmux-{{ tmux_tag }}.tar.gz"
        mode: '0644'

    - name: Extract tmux source
      unarchive:
        src: "{{ tmux_build_dir }}/tmux-{{ tmux_tag }}.tar.gz"
        dest: "{{ tmux_build_dir }}"
        remote_src: yes

    - name: Find extracted directory
      find:
        paths: "{{ tmux_build_dir }}"
        file_type: directory
        patterns: "tmux-tmux-*"
      register: tmux_source_dir

    - name: Configure tmux build
      shell: |
        cd "{{ tmux_source_dir.files[0].path }}"
        sh autogen.sh
        ./configure --prefix={{ tmux_install_prefix }}
      args:
        chdir: "{{ tmux_source_dir.files[0].path }}"

    - name: Compile tmux
      shell: |
        cd "{{ tmux_source_dir.files[0].path }}"
        make -j{{ ansible_processor_vcpus }}
      args:
        chdir: "{{ tmux_source_dir.files[0].path }}"

    - name: Install tmux
      shell: |
        cd "{{ tmux_source_dir.files[0].path }}"
        make install
      args:
        chdir: "{{ tmux_source_dir.files[0].path }}"

    - name: Clean up build directory
      file:
        path: "{{ tmux_build_dir }}"
        state: absent

    - name: Verify tmux installation
      command: "{{ tmux_binary_path }} -V"
      register: tmux_version_check
      changed_when: false

    - name: Display tmux installation success
      debug:
        msg: |
          tmux installed successfully!
          Version: {{ tmux_version_check.stdout }}
          Location: {{ tmux_binary_path }}

  when: not tmux_exists.stat.exists
  rescue:
    - name: Clean up on failure
      file:
        path: "{{ tmux_build_dir }}"
        state: absent
      ignore_errors: yes

    - name: Display installation failure
      fail:
        msg: "tmux installation failed. Build directory cleaned up."