---
# Pure development environment setup playbook
# This playbook focuses only on modern development tools without legacy tasks
- name: Development Environment Setup
  hosts: all
  gather_facts: true
  vars:
    dev_user: "{{ ansible_user | default('stonecharioteer') }}"
    dev_home: "/home/{{ dev_user }}"
    
  pre_tasks:
    - name: Install essential system packages
      package:
        name:
          - curl
          - wget
          - git
          - unzip
          - tar
          - gzip
        state: present

  roles:
    - system-deps
    - cli-tools
    - dev-folders
    - tmux-from-source
    - neovim-latest
    - tree-sitter-cli
    - astronvim-config
    - docker

  post_tasks:
    - name: Display development environment setup completion
      debug:
        msg: |
          🚀 Development Environment Setup Complete!
          
          ✓ System dependencies and development headers
            - Build tools (gcc, make, cmake, autotools)
            - Development libraries (ssl, ffi, readline, sqlite)
            - Python3 system packages (no compilation)
            - Essential utilities (curl, git, htop)
          
          ✓ Modern CLI tools installed
            - File search: ripgrep, fd-find, fzf
            - Directory tools: tree, zoxide  
            - Development: direnv, httpie
            - File watching: watchexec-cli (via cargo binstall)
            - Terminal UI: starship prompt, gum
            - Utilities: cowsay, fortune, lolcat, neofetch
          
          ✓ Development folder structure created
            - ~/code/checkouts/{personal,work}/
            - ~/code/tools/
            - ~/workspace/{projects,scratch}/
            - ~/Pictures/screenshots/
            - ~/.local/bin/
          
          ✓ tmux compiled from source (latest version)
            - Installed to /usr/local/bin/tmux
            - All dependencies satisfied
          
          ✓ Neovim {{ neovim_version }} installed
            - Binary: /usr/local/bin/nvim
            - Vim symlink: /usr/local/bin/vim
          
          ✓ tree-sitter CLI via npm/mise
            - Requires Node.js from mise (fish ansible setup)
          
          ✓ AstroNvim configuration installed
            - Configuration: ~/.config/nvim
            - Plugins installed headlessly
          
          ✓ Docker Engine installed
            - Latest Docker CE with Compose plugin
            - User added to docker group
            - Services enabled for boot
          
          📋 Next Steps:
          1. Log out and log back in for group/PATH updates
          2. Test Docker: docker run hello-world
          3. Run 'nvim' to complete any remaining plugin setup
          4. Install language servers: ':LspInstall <server>'
          5. Install language parsers: ':TSInstall <language>'
          
          📋 Prerequisites (run separately):
          - Fish shell setup with mise (Node.js, Python, Go, Rust)
          - Fonts installation (JetBrains Mono Nerd Font)
          
          🔧 For a complete system setup, use:
          - playbooks/gui.yml (GUI machines)
          - playbooks/servers.yml (headless servers)  
          - playbooks/laptops.yml (laptops)