---
# For all headless development servers
- hosts: all
  gather_facts: true
  tasks:
    - import_tasks: tasks/build-dependencies.yml
    - import_tasks: tasks/rust.yml
    - import_tasks: tasks/python/build-dependencies.yml
    - import_tasks: tasks/tmux.yml
    - import_tasks: tasks/neovim.yml
    - import_tasks: tasks/dev-tools.yml
    - import_tasks: tasks/fish.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/python/3.9.yml
