---
# this is the playbook that I need for servers.
- hosts: all
  gather_facts: yes

  tasks:
    - name: Print Distribution Names
      debug: msg="{{ ansible_distribution }}"
    - name: Install Packages in Ubuntu
      when: ansible_facts["os_family"] == "Debian"
      block: 
        - name: Install Ubuntu Packages
          become: yes
          apt:
            update_cache: yes
            state: present
            pkg:
              - build-essential
              - busybox-static
              - curl
              - gdb
              - git
              - lcov 
              - libbz2-dev
              - libffi-dev
              - libgdbm-compat-dev
              - libgdbm-dev
              - liblzma-dev
              - libncurses5-dev
              - libncursesw5-dev
              - libreadline-dev
              - libreadline6-dev
              - libsqlite3-dev
              - libssl-dev
              - libxml2-dev
              - libxslt-dev
              - llvm
              - lzma
              - lzma-dev
              - make
              - most
              - netcat-openbsd
              - pkg-config
              - python3-openssl
              - sqlite3
              - tcl
              - tk-dev
              - tmux
              - tree
              - uuid-dev
              - vim
              - wget
              - xz-utils
              - zlib1g-dev
    - name: Ensure the locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present
      register: en_us_utf_8_locale_generated
    - name: Reboot if locale generated.
      reboot:
      when: en_us_utf_8_locale_generated.changed
    - name: set as default locale
      command: localectl set-locale LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
    - name: Install Packages in Arch Linux and Manjaro
      when: ansible_facts["os_family"] == "Archlinux"
      block:
        - name: Update Pacman Package Sources
          become: yes
          pacman:
            update_cache: yes
        - name: Install Arch Packages
          become: yes
          pacman:
            name:
              - git
              - curl
              - httpie
              - base-devel
            state: present
